---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: 'Contenido '
- type: jekyll-posts
  label: 'Publicaciones '
  create: all
  templates:
  - post
- type: jekyll-pages
  label: 'Paginas '
  create: all
  templates:
  - landing-page
  - page
- type: directory
  path: _people
  label: 'Personas '
  create: all
  match: "*"
  templates:
  - person
- type: directory
  path: _projects
  label: Proyectos
  create: all
  match: "*"
  templates:
  - project
- type: document
  path: _data/information.yml
  label: 'Contacto '
upload_dir: FUNSADERE
public_path: https://res.cloudinary.com/dh7dywhsr/image/upload/funsadere
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename/:filename:"
instant_preview: false
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
